name: Handle Order Form Submission

on:
  workflow_dispatch:  # Allow manual triggering
  repository_dispatch:  # Trigger via API

jobs:
  handle-order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send order to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # Replace with your form data (this is just an example)
          TELEGRAM_USERNAME="TestUser"
          SERVICE="Test Service"
          DETAILS="This is a test order."

          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "username": "Order Bot",
              "avatar_url": "https://i.imgur.com/a/A3zGHbh",
              "embeds": [{
                "title": "📬 New Order Received",
                "color": 0x8A2BE2,
                "fields": [
                  { "name": "Service", "value": "'"$SERVICE"'", "inline": true },
                  { "name": "Telegram Username", "value": "'"$TELEGRAM_USERNAME"'", "inline": true },
                  { "name": "Project Details", "value": "'"$DETAILS"'" }
                ],
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
                "footer": {
                  "text": "Mohamed Pro Services Order System",
                  "icon_url": "https://i.imgur.com/a/A3zGHbh"
                }
              }]
            }' \
            "$DISCORD_WEBHOOK_URL"
